### ISSUE TITLE
Modify the lab to use Github.io hosting

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab1_HTML-CSS#12]
It wouldn't take a lot of work to modify the lab so that people could easily use Github.io hosting to see their web page.

Since Github.io hosting is branch based, this would be a good place to enforce working in feature branches and, if we wanted to get that fancy, requiring pull requests to bring features into the published branch.

**Comment by joethe** [comment]
I've added some basic stuff to the readme regarding this, but I think it might need a second look.

**Comment by devshawn** [comment]
I'll take a look at this later today or tomorrow.

**Comment by floogulinc** [comment]
ghpages hosting is no longer branch based. You can set it right in the repo settings to use the root of the main branch, a seperate branch, or a folder in the main branch.

**Comment by floogulinc** [comment]
You can also have just a folder of a branch be published.

**Comment by joethe** [comment]
This should be relativity simple to get finished up. I'm going to move this along a little. Please voice opinions. 😄

**Comment by kklamberty** [comment]
The work that @joethe suggested was good. This is added and done.
