### ISSUE TITLE
Add an ugly CSS component to the project

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab1_HTML-CSS#14]
@kklamberty used to have a component of a similar lab where students would create two CSS files, one of which was pretty, and one of which made the web page really ugly. This sounds potentially fun, if somewhat distracting, and we might consider adding it.

**Comment by kklamberty** [comment]
We decided this was not what we want the students to focus on - it might be fun, but we thought they'd learn more useful CSS making things look nice.
