### ISSUE TITLE
Change div structure in index.html

### ISSUE THREAD

**Issue by helloworld12321** [UMM-CSci-3601/3601-lab1_HTML-CSS#41]
Currently, the `#validation` and `#style` divs live inside the `.faculty-container` div, even though they're unrelated to the faculty. As a result, styling the faculty container—say, changing the font-size—will also affect the note about validation and the style-switcher control. Instead, `#validation` and `#style` should be siblings of `.faculty-container` and direct children of the body tag.

(Kudos to [kklamberty](https://github.com/kklamberty) for noticing this!)

**Comment by helloworld12321** [comment]
😯 Oh, you know what, this might just be a naming issue. It looks like the intention is to have `.faculty-container` be a div around *everything that wasn't* `.pslo-courses-container`. That way, you would have two classes named something like .foo-container:

1. `.pslo-courses-container`, containing `#pslo` and `#courses`, which puts its elements in a row.
2. `.faculty-container`, containing `#faculty`, `#validation`, and `#style`, which puts its elements in a column.

This explains why `.faculty-container` is styled up with so many flex-box properties: it's supposed to contain multiple children, rather than just the `#faculty` section. 🕵🏻‍♂️

Given that this is the intent of `.faculty-container`, I'm not sure what the correct path forward is—that's a design decision above my pay grade. That being said, may I throw out a few possibilities?

1. Keep `.faculty-container`, but rename it (maybe to something like `.rest-container` or `.rest`?)  so that students (like me 🙃🐑) don't misinterpret it as a div around just `#faculty`.
2. Get rid of `.faculty-container` and make `#faculty`, `#validation`, and `#style` direct children of the body tag. Rely on the flex-box properties in the body tag to lay out everything appropriately.
3. Do nothing. As it stands, the lab works, and the idea of having two top-level sections—one for `#pslo` and `#courses`, one for everything else—is a reasonable decision. The naming might be a little confusing, but it's not the worst thing that could happen. It might not be worth it to make big changes to this lab.

Anyway, that's the story! Thanks for your time! ☺️

**Comment by helloworld12321** [comment]
(Oh, looks like Prof. Nic is on it. ☺️ In that case, would someone be so kind as to mark this issue as a duplicate of #43 ?)

**Comment by helloworld12321** [comment]
Closing as a duplicate of #43—looks like Nic is on it!.

**Comment by floogulinc** [comment]
duplicate of #43
