### ISSUE TITLE
Add accessibility check to the lab

### ISSUE THREAD

**Issue by floogulinc** [UMM-CSci-3601/3601-lab1_HTML-CSS#46]
We should encourage making accessible HTML and should see if we can include some way to validate it. I think the example would need some tweaking to make it proper too.

**Comment by floogulinc** [comment]
Here are some GitHub apps that check a11y:
- https://github.com/marketplace/accesslint
- https://github.com/marketplace/axe-linter

We could also build a GitHub action using something like this: https://github.com/pa11y/pa11y

Additionally, [Lighthouse](https://developers.google.com/web/tools/lighthouse) includes a11y audits.

The U also has some resources we may find helpful: https://accessibility.umn.edu/

**Comment by NicMcPhee** [comment]
I really like this idea, and I particularly like including it in GitHub actions if possible. I don't really have time to check a lot of options at the moment, TBH, but I'd be happy to at least trial run something if you feel like there's something that ought to be reasonable.

**Comment by NicMcPhee** [comment]
For this semester we'll add a note about accessibility and a link to the U's accessibility page (up above), but not integrate any tooling right now. We have some nesting issues in our headers that we should fix, probably in another issue.

**Comment by NicMcPhee** [comment]
We may also want to turn on TSLint accessibility checks in the future Angular labs.
