### ISSUE TITLE
Change the link to Let Me Google That For You in LABTASKS.md

### ISSUE THREAD

**Issue by helloworld12321** [UMM-CSci-3601/3601-lab1_HTML-CSS#55]
Credit to @floogulinc for suggesting this.

LMGTFY has kind of gotten a bit advertising-y and gross in recent years. (Also, linking to them is probably snarkier than a lab writeup should be. 🙃)

<img width="1277" alt="Screen Shot 2021-02-03 at 6 51 17 PM" src="https://user-images.githubusercontent.com/56209343/106828950-cf85c780-6650-11eb-9ad6-0d112806ce62.png">

We were going to make this change for Spring 2021, but didn't get around to it in time. 🤷🏻‍♂️

**Comment by floogulinc** [comment]
My ad blocker seems to just block the entire results page
![image](https://user-images.githubusercontent.com/1300395/106900274-f2999100-66bb-11eb-9d78-68a19a8e9972.png)

If we wanted something true to the original intention of LMGTFY it would be this: https://letmegooglethat.com/?q=grouping+and+nesting+css

But I still think it's snarky and inappropriate for the lab.

(If we did want to just link to a Google search we can just do that: https://www.google.com/search?q=grouping+and+nesting+css)
