### ISSUE TITLE
Review readme and labtasks for any typos or potential improvments.

### ISSUE THREAD

**Issue by joethe** [UMM-CSci-3601/3601-lab1_HTML-CSS#6]
Someone should proof read these things.

Additionally, we may want to consider adding/removing requirements from LABTASKS.md

**Comment by kklamberty** [comment]
I thought we wanted to remove the parts about HTML5 and CSS3 at the end of labtasks. It was always a bit of a pain to check for those things, and not entirely clear why we should care.

**Comment by joethe** [comment]
I agree with nic (see: slack) that those requirements are likely a holdover from when those features were really new.

The upside to limiting the use of those features is that it stops clever students from taking "shortcuts" and avoiding some of the hard parts of writing a site using just HTML/CSS.

However, I think that's also a downside. Enough people will avoid learning the "fancy" features (and end up doing things the hard way) that I don't think we should have the rules to stop the handful of people who really want to get clever with it - that cleverness might be valuable later in the project.

I propose removing the limits on those features, and replacing it with a requirement that each group use at least one HTML5 and one CSS3 feature, adding notes in their readme (or as in-line comments by the use of the feature) about why they used it.

**Comment by NicMcPhee** [comment]
@joethe – I think that your changes look good to me – thanks.
